import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { connect } from "react-redux";
import NavComponents from './Navbar'


const Layout = ({ children, title, auth }) => {
    let isUser
    const router = useRouter()
    if (typeof window !== 'undefined') {
        isUser = localStorage.getItem('token')
    }

    useEffect(() => {
        if (!isUser) {
            router.push('/login')
        }
        // if (!auth.isAuthenticated) {
        //     console.log('no auth')
        //     localStorage.removeItem('token')
        //     router.push('/login')
        // }
    }, [isUser])

    console.log(auth)




    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavComponents />
            <div className='layout'>
                <main>
                    {children}
                </main>
                <footer>

                </footer>
            </div>
        </div>

    );
};

const getStateToProps = state =>({
    auth: state.auth
})

export default connect(getStateToProps)(Layout);